### ISSUE TITLE
Option for horizontal / vertical alignment?

### ISSUE THREAD

**Issue by rkusa** [aslansky/gulp-sprite#1]
First, thanks for starting the work on gulp-sprite!

Would you mind adding an option to adjust the alignment of the images in the sprite, so whether if they are appended horizontally or vertically?

**Comment by aslansky** [comment]
Yeah, that was planned for the next version. I just have to find the time to implement it.

**Comment by rkusa** [comment]
Awesome! :thumbsup: 

Grüße nach Leipzig :wink:
